### ISSUE TITLE
Update instructions from using go get to using go install

### ISSUE THREAD

**Issue by hansgylling** [mgechev/revive#737] opened 2022-08-19 15:21 UTC
**Describe the bug**
The project have some old files with instructions that tells the reader to use `go get -u` to install revive. I believe this should say `go install` nowadays. The files I have seen so far are `DEVELOPING.md` and `.github/ISSUE_TEMPLATE/bug_report.md`, but it could be a good idea to look for more instances with `grep -r -F 'go get'`

**Comment by mgechev** [comment] 2022-08-24 18:40
Hey @hansgylling do you want to open a PR with the update?

**Comment by hansgylling** [comment] 2022-08-26 12:08
Yes, I was thinking I could fix it myself. I didn't have much time when writing the bug, but could do it now. I have ran the grep command I suggested and didn't find any other file.

I will say that I'm not used to Github (we use Gitlab at work) and I haven't made any pull request on Github yet, so I will need to figure that out and may make some mistakes along the way. We'll see.

**Comment by chavacava** [comment] 2022-08-27 11:22
Hi @hansgylling, I'll be glad to help you with the PR process.

**Comment by doniacld** [comment] 2022-10-01 07:00
@chavacava I think the issue is fixed, you can close it.

**Comment by chavacava** [comment] 2022-10-01 09:43
@doniacld there are still some references to `go get` in the project documentation

**Comment by attiss** [comment] 2022-10-02 00:19
@chavacava I'd be happy contribute these updates to the docs.

**Comment by attiss** [comment] 2022-10-03 16:27
https://github.com/mgechev/revive/pull/750

**Closed** 2022-10-04 08:26 UTC
Labels: hacktoberfest

**Comment by hansgylling** [comment] 2022-10-04 08:33
Thanks for doing this. I said I would do it, but I've been very busy with work and life.
