### ISSUE TITLE
cant get revive by "go get"

### ISSUE THREAD

**Issue by 6543** [mgechev/revive#378] opened 2020-03-28 23:34 UTC
**go version go1.14.1 linux/amd**

return error if execute: `go get -u github.com/mgechev/revive`

error:
```
package golang.org/x/tools/go/gcexportdata: golang.org/x/tools is a custom import path for https://go.googlesource.com/tools, but /home/6543/go/src/golang.org/x/tools is checked out from https://github.com/golang/tools.git
package golang.org/x/tools/go/ast/astutil: golang.org/x/tools is a custom import path for https://go.googlesource.com/tools, but /home/6543/go/src/golang.org/x/tools is checked out from https://github.com/golang/tools.git
```

**Comment by mgechev** [comment] 2020-03-30 03:52
I can't reproduce it with the latest master. I'm using macOS though, unfortunately, I can't verify the behavior on linux.

**Comment by chavacava** [comment] 2020-03-30 15:48
Hi @6543,

I can not reproduce on Linux:

```
/go # cat /etc/issue
Welcome to Alpine Linux 3.11
Kernel \r on an \m (\l)
/go # go version
go version go1.14.1 linux/amd64
/go # go get -u github.com/mgechev/revive
/go # revive -h

 _ __ _____   _(_)__  _____
| '__/ _ \ \ / / \ \ / / _ \
| | |  __/\ V /| |\ V /  __/
|_|  \___| \_/ |_| \_/ \___|
```

**Comment by mgechev** [comment] 2020-04-09 16:44
Looks like the problem is not reproducible. Closing this issue.

**Closed by mgechev** 2020-04-09 16:44 UTC
