### ISSUE TITLE
Do not fail if excluded paths are missing

### ISSUE THREAD

**Issue by mark-kubacki** [mgechev/revive#568] opened 2021-08-27 19:28 UTC
Excluding a path that is absent gets an error, yet the absence should be satisfactory in the first place.

For example, reproduce in any repository, such as *revive’s* own, that has no `vendor/` (or `private/`, …):
```bash
rm -rf vendor
revive -exclude "./vendor" .
```

I’ve expected a happy run and no output related to the exclusion.

Yet got with v1.1.1:
```console
cannot find package "./vendor" in:
	vendor
```

**Comment by chavacava** [comment] 2021-08-28 11:04
Hi @wmark, thank for filling the issue. 
The root cause seems to be a bug in `dots` package.
I'll try to fix it in the next days.
Meanwhile you can use the `vendor/...` pattern to avoid the problem and get the same behavior.

**Comment by wmark** [comment] 2021-08-30 13:50
Thank you for considering this!

For some context, I am building images with **revive** with defaults that cover frequently found layouts, like this (hereby in public domain):
```Dockerfile
# A localhost/revive that can be run without arguments in your CI.
FROM localhost/golang:latest as gotools

ENV CGO_ENABLED=0
RUN go install \
  -trimpath -ldflags "-s -w" \
  github.com/mgechev/revive@latest

FROM gcr.io/distroless/static
VOLUME ["/go"]
WORKDIR /go
COPY --from=gotools /go/bin/revive /usr/bin/
ENTRYPOINT ["/usr/bin/revive"]
CMD ["-exclude", "./vendor", "-exclude", "./private", "-exclude", "./.git", "."]
```

**Comment by mgechev** [comment] 2021-09-22 19:16
Just merged the PR in dots. @chavacava thanks for the fix!

**Closed as completed by mgechev** 2021-09-22 19:16 UTC
